name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "branch-cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: echo "Instalando dependencias..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Simulation
        run: echo "Realizando o deploy..."